### ISSUE TITLE
Support serial mode on Mac OS

### ISSUE THREAD

**Issue by Windsplunts** [goburrow/modbus#1]
On OS X Yosemite with XCode command line tools and binary installed Golang, go get fails. Here is my command prompt window 

![image](https://cloud.githubusercontent.com/assets/1868926/6011505/7f588b56-ab0a-11e4-80e7-b0283a089ba8.png)

**Comment by vietnq** [comment]
Thanks for reporting, I don't have a Mac so I haven't implemented serialPort on that platform yet. I'll give a shot soon.

**Comment by nqv** [comment]
Should work now per https://github.com/goburrow/serial/pull/1
