### ISSUE TITLE
low and high bytes are switched in CRC

### ISSUE THREAD

**Issue by xiegeo** [goburrow/modbus#14]
This "bug" does not effect usage, only an internal naming confusion.

See reference http://www.modbus.org/docs/Modbus_over_serial_line_V1_02.pdf page 39 and 42.

The low byte should be serialized before the high byte, but it is the opposite in source code. The switch also happens when low byte and high byte are computed, the two switches resulting in the correct CRC written.

**Comment by nqv** [comment]
You are right. I don't remember which doc I referred when working on that. Will fix, also PR is welcome :)

**Comment by xiegeo** [comment]
I'll send a PR.

**Comment by xiegeo** [comment]
See PR #15
