### ISSUE TITLE
Unexpected disconnects from ClientHandlers.

### ISSUE THREAD

**Issue by OrangeTux** [goburrow/modbus#16]
While investigating why one of our server experiences thousands of connections being in TIME_WAIT state I discovered an undocumented and unexpected side effect of [modbus.TCPClientHandler.Send()`](https://github.com/goburrow/modbus/blob/master/tcpclient.go#L138):

``` go
if mb.conn == nil {
		// Establish a new connection and close it when complete
		if err = mb.Connect(); err != nil {
			return
		}
		defer mb.Close()
}
```

When `Send()` is called and a connection has not been it established yet, the `Send()` connects for 1 request and then disconnects. A similar implementation can be found in `modbus.ASCIIClientHandler` and `modbus.RTUClientHandler.Send()`.

I don't think it's the responsability of the `Send()` method to connect and disconnect implicitly. This should be done explicitly.  Connecting and reconnecting for every request is a waste of resources , especially for embedded devices which we use. It also gives room for errors, because one doesn't has to explicitly call `TCPCLientHandler.Connect()` before doing a request.

I removed the above code fragment and did a quick tests. And because the connection is now reused properly I saw a major drop the amount of connections in TIME WAIT state. The number dropped from around 2600 to 14.

![time_wait](https://cloud.githubusercontent.com/assets/1565144/23036417/0d884376-f483-11e6-8f8c-06338a647432.png)

**Comment by nqv** [comment]
You're right, I haven't documented it thoroughly, just this line is README isn't enough:

> // Connect manually so that multiple requests are handled in one connection session

I just want to make the ClientHandler like `http.Transport`. May be I should only close the connection after a period of inactive.
