### ISSUE TITLE
Output formatting inconsistent (minor)

### ISSUE THREAD

**Issue by andig** [goburrow/modbus#28]
It would be nice if send an receive were formatted identically:

    RTUClientHandler: 2018/05/12 13:52:47 modbus: received 01 04 04 43 69 0b 7c 38 cd
    RTUClientHandler: 2018/05/12 13:52:47 modbus: sending "\x01\x04\x00\x04\x00\x020\n"

**Comment by andig** [comment]
It's this line https://github.com/goburrow/modbus/blob/0d0a427beb37599ff34f8d74617af5ac403e9700/rtuclient.go#L123 which needs to be `% x` instead of `%q` for consistency.

@nqv would you accept a PR for this? We're heavily using this library in https://github.com/gonium/gosdm630.

**Comment by nqv** [comment]
sure, please send PR - sorry I haven't done it yet

**Comment by andig** [comment]
Much appreciated, thank you!
