### ISSUE TITLE
Slave Modbus RTU over TCP 

### ISSUE THREAD

**Issue by clemansta** [goburrow/modbus#37]
I am attempting to create a holding register for simulating a modbus RTU slave. I am working in python and need some direction to create this. Any suggestions.

**Comment by dontsovcmc** [comment]
It's very useful cause there are a lot of 485-Ethernet (485-GPRS) gateways. I also need it.

**Comment by nimahkh** [comment]
Hi guys, 
is there any chance to get RTU over TCP connection?
