### ISSUE TITLE
WSARecv tcp 192.168.1.222:10454: i/o timeout,when update To go1.4.2

### ISSUE THREAD

**Issue by chengziqing** [goburrow/modbus#5]
Use of the latest code.And update To go1.4.2.

modbus.NewTCPClientHandler 
error:WSARecv tcp 192.168.1.222:10454: i/o timeout

**Comment by chengziqing** [comment]
I already know.
FuncCodeReadDiscreteInputs = 2 
modify
FuncCodeReadDiscreteInputs = 3

because FuncCodeReadDiscreteInputs is const.
I must  edit lib code.

**Comment by nqv** [comment]
@chengziqing  Would you please clarify what the issue is? Did you got i/o timeout when using ReadDiscreteInputs or ReadHoldingRegisters?
From what you've suggested, I think your server does not support function code ReadDiscreteInputs (0x02)?
