### ISSUE TITLE
reading of holding register limited to 125 bytes

### ISSUE THREAD

**Issue by pdorrestijn** [goburrow/modbus#67]
Reading quantity for holding register (and others) are limited.
Not sure why this is limited, but I would like to read quite some more.
Can I change this? Are there any limitations?

**Comment by pdorrestijn** [comment]
p.s. this would be over tcp/ip

**Comment by pdorrestijn** [comment]
Ah, just found my answer: modbus message size may not exceed 255 bytes....

**Comment by askfiy** [comment]
I also encountered this problem, is there any good solution?
@pdorrestijn
